### ISSUE TITLE
Issues 14-02-22

### ISSUE THREAD

**Issue by jrgs** [jose-hr14/Data-Access-JHR-2122#17]
1. La base de datos debe llamarse 'Library' (la l en mayúscula)
2. Al intentar recuperar un dato, me da error, puede ser que le hayas hecho algún cambio a la BD? Por ejemplo, has añadido un campo para las multas? Lo ponemos en común en clase.

**Comment by jose-hr14** [comment]
Efectivamente, el campo multas de la tabla usuario, y la creación de la tabla reservas. En clase lo vemos, un saludo.

**Comment by jrgs** [comment]
Issue número dos solventada creando yo el campo fined.
3.- Cuando termina una búsqueda, no recuperas el panel anterior.
4.- Y cuando cierro el panel, desaparece la búsqueda! 
5.- Tienes una sistemática diferente, pero se puede aceptar.
6. En préstamos, book title, pongo '12' (valor no existente) y peta
7. Cuando tengo todos los valores del préstamo ¿cómo hago para confirmarlo?
