### ISSUE TITLE
Lío

### ISSUE THREAD

**Issue by jrgs** [jose-hr14/Data-Access-JHR-2122#3]
https://github.com/jose-hr14/Data-Access-JHR-2122/blob/8e4e43d002a3bc747575a032ef44b518b2e58f67/UD02/Ex07_02/src/u2/Ex02/XmlContactHandler.java#L9-L61

¿Te has liado un poco con este ejercicio?

**Comment by jose-hr14** [comment]
Tendría que ser una aplicación que lea contactos de cualquiera de los dos formatos y escriba en cualquiera de los dos? En lugar de ser un conversor de formatos

**Comment by jrgs** [comment]
Efectivamente. El efecto que se logra es el mismo.

Un saludo

**Comment by jose-hr14** [comment]
De acuerdo, muchas gracias.
