### ISSUE TITLE
23505

### ISSUE THREAD

**Issue by jrgs** [jose-hr14/Data-Access-JHR-2122#8]
https://github.com/jose-hr14/Data-Access-JHR-2122/blob/0101e3717ec63ad83983f518c853819bb4915bb6/UD03/FinalActivity/src/main/java/org/example/Database.java#L22

¿Que quieres controlar con ésto?

**Comment by jose-hr14** [comment]
Devolver una excepción y lanzarla hacia arriba, para poder avisar desde un label en el formulario, que ya existe un estudiando con ese ID.
